# Encoding Categorical Data

- The process of changing categorical columns into numerical columns is called Encoding Categorical Data

In [46]:
import pandas as pd

In [47]:
df= pd.read_csv("./datasets/students.csv")

In [48]:
df.head()

   ID     Name  Gender   Color Education_Level Satisfaction Purchase
0   1    Fiona  Female    Blue          Master         Good      Yes
1   2    Diana  Female     Red             PhD    Excellent       No
2   3   George    Male   Green        Bachelor         Good      Yes
3   4    Julia  Female  Yellow     High School      Average       No
4   5  Charlie    Male    Blue        Bachelor         Poor      Yes

In [49]:
df= df.iloc[:, 2:]
df.sample(5)

    Gender  Color Education_Level Satisfaction Purchase
28  Female   Blue     High School         Good       No
31  Female  Green             PhD    Excellent       No
0   Female   Blue          Master         Good      Yes
27    Male  Green        Bachelor      Average      Yes
2     Male  Green        Bachelor         Good      Yes

## Ordinary Enconding
- Ordinary encoding is done for the column having  ordinary categorical data i.e the category in column are in order
- Education_level and Satisfaction are columns containing ordinary categorical data

In [50]:
# Splitting the data into train test split

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(df.iloc[:, [2, 3]], df['Purchase'], train_size= 0.7)

In [51]:
x_test

   Education_Level Satisfaction
49          Master         Poor
5           Master         Good
35          Master         Good
6              PhD    Excellent
31             PhD    Excellent
4         Bachelor         Poor
28     High School         Good
18     High School         Good
17        Bachelor      Average
37        Bachelor      Average
10        Bachelor         Good
33        Bachelor         Good
9      High School         Poor
8           Master         Good
24        Bachelor         Poor

In [52]:
# ordinary encoding
from sklearn.preprocessing import OrdinalEncoder

oe= OrdinalEncoder(categories= [['High School', 'Bachelor', 'Master', 'PhD'], ['Poor', "Average", "Good", "Excellent"]])  # no of list = no. of ordinal categorical columns. ['High School', 'Bachelor', 'Master', 'PhD']= [0,1,2,3]

# Always fit using train data
oe.fit(x_train)


#transform both train and test data
x_test= oe.transform(x_test)
x_train= oe.transform(x_train)

In [53]:
pd.DataFrame(x_test, columns= df.iloc[:, [2, 3]].columns )

    Education_Level  Satisfaction
0               2.0           0.0
1               2.0           2.0
2               2.0           2.0
3               3.0           3.0
4               3.0           3.0
5               1.0           0.0
6               0.0           2.0
7               0.0           2.0
8               1.0           1.0
9               1.0           1.0
10              1.0           2.0
11              1.0           2.0
12              0.0           0.0
13              2.0           2.0
14              1.0           0.0

## Label Encoding

- Label Encoding is same like ordinal Encoding ; ordinal encoding is for input columns whereas label encoding is for output columns.

- Note: We can use Ordinal/ Label encoding in columns having Nominal catagories if the no of category is exactly 2(binary) like yes/no etc.

In [54]:
from sklearn.preprocessing import LabelEncoder

le= LabelEncoder()  # we donot provide any arguments(order) here like in Ordinal encoder. It automatically assigns value to the catagories
le.fit(y_train)

y_test= le.transform(y_test)
y_train= le.transform(y_train)

In [55]:
y_train

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1])

## One Hot Encoding:
- It is done for Nominal Categorical Data

In [56]:
df= pd.read_csv("./datasets/vechiles.csv")

In [57]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [58]:
# split the data into train, test, splt
from sklearn.model_selection import train_test_split

x_train,  x_test,y_train, y_test= train_test_split(df.drop(columns= "selling_price"), df['selling_price'], train_size= 0.8)

In [59]:
x_train

      brand  km_driven    fuel         owner
2     Honda     140000  Petrol   Third Owner
6      Ford     150000  Petrol   Third Owner
12     Ford     125000  Diesel   Third Owner
15    Honda      90000  Petrol   First Owner
19  Hyundai      95000  Petrol   First Owner
16    Skoda     130000  Diesel   Third Owner
18     Ford     105000  Diesel  Second Owner
14   Maruti     115000  Diesel  Second Owner
4    Maruti     120000  Petrol   First Owner
7   Hyundai      80000  Petrol   First Owner
0    Maruti     145500  Diesel   First Owner
9     Honda     130000  Petrol   Third Owner
5    Toyota      90000  Diesel  Second Owner
3   Hyundai     127000  Diesel   First Owner
8    Maruti     110000  Diesel  Second Owner
1     Skoda     120000  Diesel  Second Owner

In [60]:
x_train['brand'].nunique()

6

In [61]:
x_test

      brand  km_driven    fuel         owner
11   Toyota     140000  Petrol  Second Owner
13  Hyundai     100000  Petrol   First Owner
17   Toyota     120000  Petrol   First Owner
10    Skoda      95000  Diesel   First Owner

In [62]:
# one hot encoding
# always do one hot encoding of the columns required only and later merge it with other
import numpy as np
from sklearn.preprocessing import OneHotEncoder

ohe= OneHotEncoder(sparse_output= False, dtype= np.int32, drop= 'first')   #dropes 1st column of each one hot encoded variables, sparse_output= False gives the output in np array

# fit the data
ohe.fit(x_train.iloc[:, [0, 2, 3]])
x_train_ohe= ohe.transform(x_train.iloc[:, [0, 2, 3]])
X_test_ohe= ohe.transform(x_test.iloc[:, [0, 2, 3]])

In [63]:
x_train_ohe

array([[1, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 1, 0]], dtype=int32)

In [64]:
ohe.get_feature_names_out()

array(['brand_Honda', 'brand_Hyundai', 'brand_Maruti', 'brand_Skoda',
       'brand_Toyota', 'fuel_Petrol', 'owner_Second Owner',
       'owner_Third Owner'], dtype=object)

In [65]:
pd.DataFrame(x_train_ohe, columns= ohe.get_feature_names_out())

,brand_Honda,brand_Hyundai,brand_Maruti,brand_Skoda,brand_Toyota,fuel_Petrol,owner_Second Owner,owner_Third Owner
0,1,0,0,0,0,1,0,1
1,0,0,0,0,0,1,0,1
2,0,0,0,0,0,0,0,1
3,1,0,0,0,0,1,0,0
4,0,1,0,0,0,1,0,0
5,0,0,0,1,0,0,0,1
6,0,0,0,0,0,0,1,0
7,0,0,1,0,0,0,1,0
8,0,0,1,0,0,1,0,0
9,0,1,0,0,0,1,0,0
10,0,0,1,0,0,0,0,0
11,1,0,0,0,0,1,0,1
12,0,0,0,0,1,0,1,0
13,0,1,0,0,0,0,0,0
14,0,0,1,0,0,0,1,0
15,0,0,0,1,0,0,1,0

In [66]:
x_train= x_train['km_driven'].values  
x_train

array([140000, 150000, 125000,  90000,  95000, 130000, 105000, 115000,
       120000,  80000, 145500, 130000,  90000, 127000, 110000, 120000])

In [67]:
#since it is 1d array, we need to change it to 2d to concat the columns
x_train_2d= np.reshape(x_train, shape= (-1, 1))

In [68]:
x_train_2d

array([[140000],
       [150000],
       [125000],
       [ 90000],
       [ 95000],
       [130000],
       [105000],
       [115000],
       [120000],
       [ 80000],
       [145500],
       [130000],
       [ 90000],
       [127000],
       [110000],
       [120000]])

In [69]:
# Finally concat the km_driven from x_train and these data from x_train_one

x_train= np.concat((x_train_2d, x_train_ohe), axis= 1)

In [70]:
x_train

array([[140000,      1,      0,      0,      0,      0,      1,      0,
             1],
       [150000,      0,      0,      0,      0,      0,      1,      0,
             1],
       [125000,      0,      0,      0,      0,      0,      0,      0,
             1],
       [ 90000,      1,      0,      0,      0,      0,      1,      0,
             0],
       [ 95000,      0,      1,      0,      0,      0,      1,      0,
             0],
       [130000,      0,      0,      0,      1,      0,      0,      0,
             1],
       [105000,      0,      0,      0,      0,      0,      0,      1,
             0],
       [115000,      0,      0,      1,      0,      0,      0,      1,
             0],
       [120000,      0,      0,      1,      0,      0,      1,      0,
             0],
       [ 80000,      0,      1,      0,      0,      0,      1,      0,
             0],
       [145500,      0,      0,      1,      0,      0,      0,      0,
             0],
       [130000,      1,      0,      0,      0,      0,      1,      0,
             1],
       [ 90000,      0,      0,      0,      0,      1,      0,      1,
             0],
       [127000,      0,      1,      0,      0,      0,      0,      0,
             0],
       [110000,      0,      0,      1,      0,      0,      0,      1,
             0],
       [120000,      0,      0,      0,      1,      0,      0,      1,
             0]])

In [71]:
pd.DataFrame(x_train)

         0  1  2  3  4  5  6  7  8
0   140000  1  0  0  0  0  1  0  1
1   150000  0  0  0  0  0  1  0  1
2   125000  0  0  0  0  0  0  0  1
3    90000  1  0  0  0  0  1  0  0
4    95000  0  1  0  0  0  1  0  0
5   130000  0  0  0  1  0  0  0  1
6   105000  0  0  0  0  0  0  1  0
7   115000  0  0  1  0  0  0  1  0
8   120000  0  0  1  0  0  1  0  0
9    80000  0  1  0  0  0  1  0  0
10  145500  0  0  1  0  0  0  0  0
11  130000  1  0  0  0  0  1  0  1
12   90000  0  0  0  0  1  0  1  0
13  127000  0  1  0  0  0  0  0  0
14  110000  0  0  1  0  0  0  1  0
15  120000  0  0  0  1  0  0  1  0

# Column Transformer
- Transforming each column on the basis of its property and finally merging it is so inefficient. Thats why we use column transformer whichh transforms all the columns with one pipeline the way we want so we donot have to concat each one

In [72]:
df= pd.read_csv("./datasets/customer.csv")

In [73]:
df.sample(5)

,CustomerID,Age,Annual_Income,Spending_Score,Gender,City,Education,Satisfaction_Level,Purchased
38,1039,32,50000,77,Female,Kathmandu,Bachelor's,Very High,No
26,1027,20,25000,90,Female,Pokhara,High School,Low,No
4,1005,28,42000,91,Female,Biratnagar,Bachelor's,Low,No
10,1011,26,38000,80,Female,Kathmandu,High School,High,Yes
23,1024,64,130000,22,Male,Biratnagar,PhD,Very High,Yes

In [74]:
#df= df.drop(columns= "CustomerID")

In [75]:
df.sample(5)

,CustomerID,Age,Annual_Income,Spending_Score,Gender,City,Education,Satisfaction_Level,Purchased
44,1045,28,43000,86,Female,Kathmandu,High School,Medium,No
11,1012,34,67000,60,Male,Lalitpur,Bachelor's,Very High,No
1,1002,45,82000,45,Female,Pokhara,Master's,Medium,No
2,1003,31,55000,88,Male,Lalitpur,High School,High,Yes
29,1030,48,86000,47,Male,Kathmandu,Master's,High,Yes

In [76]:
x_train, x_test, y_train, y_test= train_test_split(df.iloc[:, :-1], df['Purchased'], train_size= 0.8)

In [77]:
x_train.head()

,CustomerID,Age,Annual_Income,Spending_Score,Gender,City,Education,Satisfaction_Level
29,1030,48,86000,47,Male,Kathmandu,Master's,High
16,1017,30,47000,83,Female,Kathmandu,Master's,Low
9,1010,55,110000,35,Male,Pokhara,Master's,Medium
7,1008,38,74000,55,Male,Kathmandu,Bachelor's,Very High
22,1023,27,40000,85,Female,Kathmandu,High School,Low

In [78]:
x_train['Education'].value_counts()

Education
Master's       11
Bachelor's     11
PhD            10
High School     8
Name: count, dtype: int64

In [79]:
y_train.head()

29    Yes
16     No
9     Yes
7     Yes
22    Yes
Name: Purchased, dtype: object

In [80]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler
transformer= ColumnTransformer(
    transformers=[
('tnf1', MinMaxScaler(), ['Age', 'Spending_Score']),
('tnf2', StandardScaler(), ['Annual_Income']),
('tnf3', OneHotEncoder(sparse_output= False, drop= 'first', dtype= np.int32), ['Gender', 'City']),
('tnf4', OrdinalEncoder(categories= [['High School', "Bachelor's", "Master's", "PhD"], ['Low', "Medium", "High", "Very High"]]), ['Education','Satisfaction_Level'])
    ], remainder= "passthrough"
)


#remainder helps us to know what to do with the column we ddint transfoorm. If it is passthrough then it wont do anything to column and if it is from thwn it will drop the column
#transformer= [(name, obect, list of colm name where transformer should be appied)]

In [81]:
x_train= transformer.fit_transform(x_train)

In [82]:
transformer.get_feature_names_out()

array(['tnf1__Age', 'tnf1__Spending_Score', 'tnf2__Annual_Income',
       'tnf3__Gender_Male', 'tnf3__City_Kathmandu', 'tnf3__City_Lalitpur',
       'tnf3__City_Pokhara', 'tnf4__Education',
       'tnf4__Satisfaction_Level', 'remainder__CustomerID'], dtype=object)

In [83]:
x_train

array([[ 6.30434783e-01,  3.51351351e-01,  4.96469215e-01,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.00000000e+00,  2.00000000e+00,
         1.03000000e+03],
       [ 2.39130435e-01,  8.37837838e-01, -8.34273011e-01,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.00000000e+00,  0.00000000e+00,
         1.01700000e+03],
       [ 7.82608696e-01,  1.89189189e-01,  1.31538751e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  2.00000000e+00,  1.00000000e+00,
         1.01000000e+03],
       [ 4.13043478e-01,  4.59459459e-01,  8.70100686e-02,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  3.00000000e+00,
         1.00800000e+03],
       [ 1.73913043e-01,  8.64864865e-01, -1.07312418e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.02300000e+03],
       [ 2.60869565e-01,  9.05405405e-01, -5.61300247e-01,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  2.00000000e+00,
         1.00300000e+03],
       [ 6.52173913e-01,  2.83783784e-01,  1.14477953e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  3.00000000e+00,  2.00000000e+00,
         1.01500000e+03],
       [ 5.43478261e-01,  4.18918919e-01,  1.55253260e-01,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  3.00000000e+00,  0.00000000e+00,
         1.04000000e+03],
       [ 4.78260870e-01,  5.00000000e-01, -1.53547180e-02,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.00000000e+00,  2.00000000e+00,
         1.02600000e+03],
       [ 1.52173913e-01,  8.24324324e-01, -1.10724578e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.04100000e+03],
       [ 4.56521739e-01,  4.45945946e-01,  1.87668775e-02,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  2.00000000e+00,  2.00000000e+00,
         1.05000000e+03],
       [ 9.78260870e-01,  1.35135135e-02,  1.99781942e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.00000000e+00,  3.00000000e+00,
         1.02400000e+03],
       [ 3.69565217e-01,  6.21621622e-01, -2.88327482e-01,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.02100000e+03],
       [ 9.34782609e-01,  8.10810811e-02,  1.48599549e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  3.00000000e+00,  0.00000000e+00,
         1.03200000e+03],
       [ 1.95652174e-01,  9.45945946e-01, -1.00488099e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         1.00500000e+03],
       [ 1.52173913e-01,  7.97297297e-01, -1.14136737e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  2.00000000e+00,
         1.01100000e+03],
       [ 3.04347826e-01,  6.75675676e-01, -5.95421842e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  3.00000000e+00,
         1.04700000e+03],
       [ 8.26086957e-01,  1.62162162e-01,  1.07653634e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  3.00000000e+00,  3.00000000e+00,
         1.02800000e+03],
       [ 6.52173913e-02,  1.00000000e+00, -1.48258333e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.01400000e+03],
       [ 8.04347826e-01,  1.75675676e-01,  1.17890113e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.00000000e+00,  0.00000000e+00,
         1.04800000e+03],
       [ 2.82608696e-01,  7.56756757e-01, -7.31908224e-01,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  3.00000000e+00,
         1.03900000e+03],
       [ 8.91304348e-01,  4.05405405e-02,  9.05928361e-01,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.00000000e+00,  2.00000000e+00,
         1.03800000e+03],
       [ 5.00000000e-01,  3.91891892e-01,  2.23496451e-01,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.00000000e+00,  3.00000000e+00,
         1.02000000e+03],
       [ 0.00000000e+00,  5.94594595e-01, -1.68731290e+00,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  2.00000000e+00,
         1.00700000e+03],
       [ 1.00000000e+00,  0.00000000e+00,  1.82721144e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  3.00000000e+00,  0.00000000e+00,
         1.04400000e+03],
       [ 2.17391304e-02,  9.32432432e-01, -1.58494811e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.02700000e+03],
       [ 6.08695652e-01,  3.37837838e-01,  4.28226024e-01,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  2.00000000e+00,  2.00000000e+00,
         1.04600000e+03],
       [ 7.39130435e-01,  2.02702703e-01,  1.24714432e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.00000000e+00,  0.00000000e+00,
         1.03600000e+03],
       [ 5.65217391e-01,  3.24324324e-01,  3.59982833e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  2.00000000e+00,  1.00000000e+00,
         1.00200000e+03],
       [ 3.91304348e-01,  6.62162162e-01, -4.58935460e-01,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  3.00000000e+00,
         1.01600000e+03],
       [ 9.13043478e-01,  5.40540541e-02,  5.64712406e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.00000000e+00,  0.00000000e+00,
         1.01300000e+03],
       [ 3.26086957e-01,  5.27027027e-01, -1.51841100e-01,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  3.00000000e+00,
         1.01200000e+03],
       [ 3.47826087e-01,  5.67567568e-01, -3.90692269e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  3.00000000e+00,
         1.03100000e+03],
       [ 8.47826087e-01,  9.45945946e-02,  7.01198788e-01,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.01800000e+03],
       [ 5.21739130e-01,  2.56756757e-01, -3.56570673e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  3.00000000e+00,  0.00000000e+00,
         1.00900000e+03],
       [ 6.73913043e-01,  2.29729730e-01,  8.71806766e-01,
         1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  2.00000000e+00,  2.00000000e+00,
         1.02200000e+03],
       [ 6.52173913e-02,  9.72972973e-01, -1.44846173e+00,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
         1.04900000e+03],
       [ 6.95652174e-01,  2.43243243e-01,  1.00829315e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.00000000e+00,  2.00000000e+00,
         1.04200000e+03],
       [ 8.69565217e-02,  6.89189189e-01, -1.24373216e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         1.00100000e+03],
       [ 2.17391304e-01,  7.83783784e-01, -9.36637797e-01,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.00000000e+00,  1.00000000e+00,
         1.02900000e+03]])

In [84]:
np.round(x_train, 2)

array([[ 6.300e-01,  3.500e-01,  5.000e-01,  1.000e+00,  1.000e+00,
         0.000e+00,  0.000e+00,  2.000e+00,  2.000e+00,  1.030e+03],
       [ 2.400e-01,  8.400e-01, -8.300e-01,  0.000e+00,  1.000e+00,
         0.000e+00,  0.000e+00,  2.000e+00,  0.000e+00,  1.017e+03],
       [ 7.800e-01,  1.900e-01,  1.320e+00,  1.000e+00,  0.000e+00,
         0.000e+00,  1.000e+00,  2.000e+00,  1.000e+00,  1.010e+03],
       [ 4.100e-01,  4.600e-01,  9.000e-02,  1.000e+00,  1.000e+00,
         0.000e+00,  0.000e+00,  1.000e+00,  3.000e+00,  1.008e+03],
       [ 1.700e-01,  8.600e-01, -1.070e+00,  0.000e+00,  1.000e+00,
         0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,  1.023e+03],
       [ 2.600e-01,  9.100e-01, -5.600e-01,  1.000e+00,  0.000e+00,
         1.000e+00,  0.000e+00,  0.000e+00,  2.000e+00,  1.003e+03],
       [ 6.500e-01,  2.800e-01,  1.140e+00,  0.000e+00,  0.000e+00,
         0.000e+00,  1.000e+00,  3.000e+00,  2.000e+00,  1.015e+03],
       [ 5.400e-01,  4.200e-01,  1.600e-01,  1.000e+00,  0.000e+00,
         0.000e+00,  1.000e+00,  3.000e+00,  0.000e+00,  1.040e+03],
       [ 4.800e-01,  5.000e-01, -2.000e-02,  1.000e+00,  1.000e+00,
         0.000e+00,  0.000e+00,  2.000e+00,  2.000e+00,  1.026e+03],
       [ 1.500e-01,  8.200e-01, -1.110e+00,  0.000e+00,  0.000e+00,
         1.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,  1.041e+03],
       [ 4.600e-01,  4.500e-01,  2.000e-02,  1.000e+00,  0.000e+00,
         1.000e+00,  0.000e+00,  2.000e+00,  2.000e+00,  1.050e+03],
       [ 9.800e-01,  1.000e-02,  2.000e+00,  1.000e+00,  0.000e+00,
         0.000e+00,  0.000e+00,  3.000e+00,  3.000e+00,  1.024e+03],
       [ 3.700e-01,  6.200e-01, -2.900e-01,  0.000e+00,  0.000e+00,
         1.000e+00,  0.000e+00,  1.000e+00,  1.000e+00,  1.021e+03],
       [ 9.300e-01,  8.000e-02,  1.490e+00,  1.000e+00,  0.000e+00,
         1.000e+00,  0.000e+00,  3.000e+00,  0.000e+00,  1.032e+03],
       [ 2.000e-01,  9.500e-01, -1.000e+00,  0.000e+00,  0.000e+00,
         0.000e+00,  0.000e+00,  1.000e+00,  0.000e+00,  1.005e+03],
       [ 1.500e-01,  8.000e-01, -1.140e+00,  0.000e+00,  1.000e+00,
         0.000e+00,  0.000e+00,  0.000e+00,  2.000e+00,  1.011e+03],
       [ 3.000e-01,  6.800e-01, -6.000e-01,  0.000e+00,  0.000e+00,
         0.000e+00,  0.000e+00,  1.000e+00,  3.000e+00,  1.047e+03],
       [ 8.300e-01,  1.600e-01,  1.080e+00,  1.000e+00,  0.000e+00,
         1.000e+00,  0.000e+00,  3.000e+00,  3.000e+00,  1.028e+03],
       [ 7.000e-02,  1.000e+00, -1.480e+00,  1.000e+00,  1.000e+00,
         0.000e+00,  0.000e+00,  0.000e+00,  1.000e+00,  1.014e+03],
       [ 8.000e-01,  1.800e-01,  1.180e+00,  1.000e+00,  1.000e+00,
         0.000e+00,  0.000e+00,  3.000e+00,  0.000e+00,  1.048e+03],
       [ 2.800e-01,  7.600e-01, -7.300e-01,  0.000e+00,  1.000e+00,
         0.000e+00,  0.000e+00,  1.000e+00,  3.000e+00,  1.039e+03],
       [ 8.900e-01,  4.000e-02,  9.100e-01,  1.000e+00,  0.000e+00,
         0.000e+00,  0.000e+00,  2.000e+00,  2.000e+00,  1.038e+03],
       [ 5.000e-01,  3.900e-01,  2.200e-01,  1.000e+00,  1.000e+00,
         0.000e+00,  0.000e+00,  3.000e+00,  3.000e+00,  1.020e+03],
       [ 0.000e+00,  5.900e-01, -1.690e+00,  0.000e+00,  0.000e+00,
         1.000e+00,  0.000e+00,  0.000e+00,  2.000e+00,  1.007e+03],
       [ 1.000e+00,  0.000e+00,  1.830e+00,  1.000e+00,  0.000e+00,
         0.000e+00,  1.000e+00,  3.000e+00,  0.000e+00,  1.044e+03],
       [ 2.000e-02,  9.300e-01, -1.580e+00,  0.000e+00,  0.000e+00,
         0.000e+00,  1.000e+00,  0.000e+00,  0.000e+00,  1.027e+03],
       [ 6.100e-01,  3.400e-01,  4.300e-01,  1.000e+00,  0.000e+00,
         1.000e+00,  0.000e+00,  2.000e+00,  2.000e+00,  1.046e+03],
       [ 7.400e-01,  2.000e-01,  1.250e+00,  1.000e+00,  1.000e+00,
         0.000e+00,  0.000e+00,  3.000e+00,  0.000e+00,  1.036e+03],
       [ 5.700e-01,  3.200e-01,  3.600e-01,  0.000e+00,  0.000e+00,
         0.000e+00,  1.000e+00,  2.000e+00,  1.000e+00,  1.002e+03],
       [ 3.900e-01,  6.600e-01, -4.600e-01,  1.000e+00,  0.000e+00,
         1.000e+00,  0.000e+00,  1.000e+00,  3.000e+00,  1.016e+03],
       [ 9.100e-01,  5.000e-02,  5.600e-01,  0.000e+00,  0.000e+00,
         0.000e+00,  0.000e+00,  2.000e+00,  0.000e+00,  1.013e+03],
       [ 3.300e-01,  5.300e-01, -1.500e-01,  1.000e+00,  0.000e+00,
         1.000e+00,  0.000e+00,  1.000e+00,  3.000e+00,  1.012e+03],
       [ 3.500e-01,  5.700e-01, -3.900e-01,  0.000e+00,  0.000e+00,
         0.000e+00,  1.000e+00,  1.000e+00,  3.000e+00,  1.031e+03],
       [ 8.500e-01,  9.000e-02,  7.000e-01,  1.000e+00,  0.000e+00,
         0.000e+00,  0.000e+00,  1.000e+00,  1.000e+00,  1.018e+03],
       [ 5.200e-01,  2.600e-01, -3.600e-01,  0.000e+00,  0.000e+00,
         0.000e+00,  0.000e+00,  3.000e+00,  0.000e+00,  1.009e+03],
       [ 6.700e-01,  2.300e-01,  8.700e-01,  1.000e+00,  0.000e+00,
         0.000e+00,  1.000e+00,  2.000e+00,  2.000e+00,  1.022e+03],
       [ 7.000e-02,  9.700e-01, -1.450e+00,  0.000e+00,  0.000e+00,
         0.000e+00,  1.000e+00,  0.000e+00,  1.000e+00,  1.049e+03],
       [ 7.000e-01,  2.400e-01,  1.010e+00,  1.000e+00,  1.000e+00,
         0.000e+00,  0.000e+00,  2.000e+00,  2.000e+00,  1.042e+03],
       [ 9.000e-02,  6.900e-01, -1.240e+00,  1.000e+00,  1.000e+00,
         0.000e+00,  0.000e+00,  1.000e+00,  0.000e+00,  1.001e+03],
       [ 2.200e-01,  7.800e-01, -9.400e-01,  0.000e+00,  0.000e+00,
         0.000e+00,  0.000e+00,  1.000e+00,  1.000e+00,  1.029e+03]])

In [85]:
pd.DataFrame(np.round(x_train, 2), columns= transformer.get_feature_names_out()).sample(5)

,tnf1__Age,tnf1__Spending_Score,tnf2__Annual_Income,tnf3__Gender_Male,tnf3__City_Kathmandu,tnf3__City_Lalitpur,tnf3__City_Pokhara,tnf4__Education,tnf4__Satisfaction_Level,remainder__CustomerID
14,0.20,0.95,-1.00,0.0,0.0,0.0,0.0,1.0,0.0,1005.0
8,0.48,0.50,-0.02,1.0,1.0,0.0,0.0,2.0,2.0,1026.0
21,0.89,0.04,0.91,1.0,0.0,0.0,0.0,2.0,2.0,1038.0
32,0.35,0.57,-0.39,0.0,0.0,0.0,1.0,1.0,3.0,1031.0
38,0.09,0.69,-1.24,1.0,1.0,0.0,0.0,1.0,0.0,1001.0

In [86]:
# label encoding
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
le.fit(y_train)
y_train=le.transform(y_train)
y_test= le.fit(y_test)

In [87]:
y_train

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

In [ ]:
le.get