In [62]:
import pandas as pd
import numpy as np

In [63]:
df= pd.read_csv("./data.csv")

In [64]:
df

    cgpa   iq  scholarship
0    9.1  135            1
1    8.7  128            1
2    8.5  120            1
3    8.9  132            1
4    9.3  140            1
5    8.2  118            1
6    8.8  125            1
7    9.0  138            1
8    7.8  115            1
9    8.4  122            1
10   6.5  105            0
11   6.8  110            0
12   7.0  108            0
13   5.9  100            0
14   6.2  102            0
15   7.1  109            0
16   6.7  107            0
17   5.5   95            0
18   6.0   98            0
19   7.2  112            0
20   9.5  145            1
21   9.2  138            1
22   8.6  126            1
23   8.3  121            1
24   7.9  117            1
25   8.1  119            1
26   9.4  142            1
27   8.0  116            1
28   7.7  114            1
29   8.5  123            1
30   5.8   97            0
31   6.3  101            0
32   6.9  106            0
33   7.0  104            0
34   6.1   99            0
35   5.7   96            0
36   6.4  103            0
37   7.3  111            0
38   6.6  105            0
39   5.6   94            0
40   9.6  148            1
41   9.0  136            1
42   8.7  129            1
43   8.2  120            1
44   7.8  118            1
45   8.9  134            1
46   9.3  141            1
47   8.4  124            1
48   7.6  113            1
49   8.1  119            1

In [65]:
x= df.drop(columns= "scholarship")

# StandardScaler
    - Scaler is used tp bring the data of a feature/columns in certain Range

In [66]:
# split the data into train test
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(x, df['scholarship'], test_size= 0.2)

In [67]:
x_train

    cgpa   iq
34   6.1   99
25   8.1  119
17   5.5   95
23   8.3  121
37   7.3  111
21   9.2  138
22   8.6  126
5    8.2  118
20   9.5  145
41   9.0  136
40   9.6  148
31   6.3  101
3    8.9  132
29   8.5  123
43   8.2  120
8    7.8  115
27   8.0  116
24   7.9  117
49   8.1  119
48   7.6  113
35   5.7   96
32   6.9  106
2    8.5  120
47   8.4  124
44   7.8  118
39   5.6   94
26   9.4  142
6    8.8  125
7    9.0  138
19   7.2  112
33   7.0  104
46   9.3  141
1    8.7  128
16   6.7  107
36   6.4  103
14   6.2  102
45   8.9  134
12   7.0  108
42   8.7  129
10   6.5  105

In [68]:
y_train

34    0
25    1
17    0
23    1
37    0
21    1
22    1
5     1
20    1
41    1
40    1
31    0
3     1
29    1
43    1
8     1
27    1
24    1
49    1
48    1
35    0
32    0
2     1
47    1
44    1
39    0
26    1
6     1
7     1
19    0
33    0
46    1
1     1
16    0
36    0
14    0
45    1
12    0
42    1
10    0
Name: scholarship, dtype: int64

In [69]:
# scale the data

from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()

scaler.fit(x_train)   #Always fit the data using x_train to know mean and standard deviation


x_train_scaled= scaler.transform(x_train)  #only scale the independent variable 
x_test_scaled= scaler.transform(x_test)

In [70]:
x_train_scaled

array([[-1.50174242, -1.36937697],
       [ 0.22937276,  0.02085346],
       [-2.02107697, -1.64742305],
       [ 0.40248428,  0.1598765 ],
       [-0.46307331, -0.53523871],
       [ 1.18148611,  1.34157236],
       [ 0.66215155,  0.5074341 ],
       [ 0.31592852, -0.04865806],
       [ 1.44115338,  1.828153  ],
       [ 1.00837459,  1.20254932],
       [ 1.52770914,  2.03668757],
       [-1.3286309 , -1.23035392],
       [ 0.92181883,  0.92450323],
       [ 0.5755958 ,  0.29889954],
       [ 0.31592852,  0.09036498],
       [-0.03029452, -0.25719263],
       [ 0.142817  , -0.18768111],
       [ 0.05626124, -0.11816959],
       [ 0.22937276,  0.02085346],
       [-0.20340603, -0.39621567],
       [-1.84796545, -1.57791153],
       [-0.80929634, -0.88279632],
       [ 0.5755958 ,  0.09036498],
       [ 0.48904004,  0.36841106],
       [-0.03029452, -0.04865806],
       [-1.93452121, -1.71693457],
       [ 1.35459763,  1.61961844],
       [ 0.83526307,  0.43792258],
       [ 1.00837459,  1.34157236],
       [-0.54962907, -0.46572719],
       [-0.72274059, -1.02181936],
       [ 1.26804187,  1.55010692],
       [ 0.74870731,  0.64645715],
       [-0.98240786, -0.8132848 ],
       [-1.24207514, -1.09133088],
       [-1.41518666, -1.1608424 ],
       [ 0.92181883,  1.06352627],
       [-0.72274059, -0.74377328],
       [ 0.74870731,  0.71596867],
       [-1.15551938, -0.95230784]])

In [71]:
# converting the np array into a dataframe

x_scaled= pd.DataFrame(x_train_scaled, columns= x.columns)
x_scaled

        cgpa        iq
0  -1.501742 -1.369377
1   0.229373  0.020853
2  -2.021077 -1.647423
3   0.402484  0.159876
4  -0.463073 -0.535239
5   1.181486  1.341572
6   0.662152  0.507434
7   0.315929 -0.048658
8   1.441153  1.828153
9   1.008375  1.202549
10  1.527709  2.036688
11 -1.328631 -1.230354
12  0.921819  0.924503
13  0.575596  0.298900
14  0.315929  0.090365
15 -0.030295 -0.257193
16  0.142817 -0.187681
17  0.056261 -0.118170
18  0.229373  0.020853
19 -0.203406 -0.396216
20 -1.847965 -1.577912
21 -0.809296 -0.882796
22  0.575596  0.090365
23  0.489040  0.368411
24 -0.030295 -0.048658
25 -1.934521 -1.716935
26  1.354598  1.619618
27  0.835263  0.437923
28  1.008375  1.341572
29 -0.549629 -0.465727
30 -0.722741 -1.021819
31  1.268042  1.550107
32  0.748707  0.646457
33 -0.982408 -0.813285
34 -1.242075 -1.091331
35 -1.415187 -1.160842
36  0.921819  1.063526
37 -0.722741 -0.743773
38  0.748707  0.715969
39 -1.155519 -0.952308

In [72]:
x.columns  # we can give columns name while creating dataframe by using the list

Index(['cgpa', 'iq'], dtype='object')

In [73]:
#Train the model
from sklearn.linear_model import LogisticRegression

model= LogisticRegression()

model.fit(x_scaled, y_train)

LogisticRegression()

In [74]:
x_test_scaled= pd.DataFrame(x_test_scaled, columns= x.columns
                            )
x_test_scaled

       cgpa        iq
0 -1.588298 -1.438888
1 -0.116850 -0.326704
2 -0.895852 -0.604750
3 -0.636185 -0.674262
4  1.094930  1.133038
5 -1.761410 -1.508400
6 -1.674854 -1.299865
7  0.489040  0.229388
8  1.268042  1.480595
9 -1.068964 -0.952308

In [75]:
y_pred= model.predict(x_test_scaled)
y_pred

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [76]:
y_test

18    0
28    1
11    0
15    0
0     1
30    0
13    0
9     1
4     1
38    0
Name: scholarship, dtype: int64