In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv("./data.csv")

In [3]:
df

    cgpa   iq  scholarship
0    9.1  135            1
1    8.7  128            1
2    8.5  120            1
3    8.9  132            1
4    9.3  140            1
5    8.2  118            1
6    8.8  125            1
7    9.0  138            1
8    7.8  115            1
9    8.4  122            1
10   6.5  105            0
11   6.8  110            0
12   7.0  108            0
13   5.9  100            0
14   6.2  102            0
15   7.1  109            0
16   6.7  107            0
17   5.5   95            0
18   6.0   98            0
19   7.2  112            0
20   9.5  145            1
21   9.2  138            1
22   8.6  126            1
23   8.3  121            1
24   7.9  117            1
25   8.1  119            1
26   9.4  142            1
27   8.0  116            1
28   7.7  114            1
29   8.5  123            1
30   5.8   97            0
31   6.3  101            0
32   6.9  106            0
33   7.0  104            0
34   6.1   99            0
35   5.7   96            0
36   6.4  103            0
37   7.3  111            0
38   6.6  105            0
39   5.6   94            0
40   9.6  148            1
41   9.0  136            1
42   8.7  129            1
43   8.2  120            1
44   7.8  118            1
45   8.9  134            1
46   9.3  141            1
47   8.4  124            1
48   7.6  113            1
49   8.1  119            1

In [4]:
x= df.drop(columns= "scholarship")

# Standardization

## StandardScaling
    - Scaler is used tp bring the data of a feature/columns in certain Range
    - xi= (xi-mean)/ standard deviation
    - does mean centering
    - mean of new data will alwaye be 0 and std. deviation is 1

In [5]:
# split the data into train test
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(x, df['scholarship'], test_size= 0.2)

In [6]:
x_train

    cgpa   iq
35   5.7   96
17   5.5   95
36   6.4  103
33   7.0  104
14   6.2  102
7    9.0  138
12   7.0  108
6    8.8  125
23   8.3  121
30   5.8   97
46   9.3  141
42   8.7  129
8    7.8  115
2    8.5  120
48   7.6  113
25   8.1  119
32   6.9  106
20   9.5  145
19   7.2  112
13   5.9  100
21   9.2  138
41   9.0  136
0    9.1  135
39   5.6   94
4    9.3  140
24   7.9  117
9    8.4  122
37   7.3  111
44   7.8  118
47   8.4  124
28   7.7  114
43   8.2  120
10   6.5  105
27   8.0  116
34   6.1   99
31   6.3  101
22   8.6  126
5    8.2  118
11   6.8  110
15   7.1  109

In [7]:
y_train

35    0
17    0
36    0
33    0
14    0
7     1
12    0
6     1
23    1
30    0
46    1
42    1
8     1
2     1
48    1
25    1
32    0
20    1
19    0
13    0
21    1
41    1
0     1
39    0
4     1
24    1
9     1
37    0
44    1
47    1
28    1
43    1
10    0
27    1
34    0
31    0
22    1
5     1
11    0
15    0
Name: scholarship, dtype: int64

In [8]:
# scale the data

from sklearn.preprocessing import StandardScaler

scaler= StandardScaler()

scaler.fit(x_train)   #Always fit the data using x_train to know mean and standard deviation


x_train_scaled= scaler.transform(x_train)  #only scale the independent variable 
x_test_scaled= scaler.transform(x_test)

In [9]:
x_train_scaled

array([[-1.63976132, -1.44642862],
       [-1.81079249, -1.5185697 ],
       [-1.04115223, -0.94144107],
       [-0.52805873, -0.8693    ],
       [-1.2121834 , -1.01358215],
       [ 1.18225295,  1.58349667],
       [-0.52805873, -0.58073568],
       [ 1.01122178,  0.64566265],
       [ 0.58364386,  0.35709834],
       [-1.55424573, -1.37428755],
       [ 1.4387997 ,  1.79991991],
       [ 0.92570619,  0.93422697],
       [ 0.15606594, -0.07574813],
       [ 0.75467503,  0.28495726],
       [-0.01496523, -0.22003029],
       [ 0.41261269,  0.21281618],
       [-0.61357431, -0.72501784],
       [ 1.60983086,  2.08848422],
       [-0.35702756, -0.29217137],
       [-1.46873015, -1.15786431],
       [ 1.35328411,  1.58349667],
       [ 1.18225295,  1.43921452],
       [ 1.26776853,  1.36707344],
       [-1.7252769 , -1.59071078],
       [ 1.4387997 ,  1.72777883],
       [ 0.24158152,  0.06853402],
       [ 0.66915944,  0.42923942],
       [-0.27151198, -0.36431245],
       [ 0.15606594,  0.1406751 ],
       [ 0.66915944,  0.57352157],
       [ 0.07055036, -0.14788921],
       [ 0.49812828,  0.28495726],
       [-0.95563665, -0.79715892],
       [ 0.32709711, -0.00360705],
       [-1.29769898, -1.23000539],
       [-1.12666782, -1.08572323],
       [ 0.84019061,  0.71780373],
       [ 0.49812828,  0.1406751 ],
       [-0.6990899 , -0.43645353],
       [-0.44254315, -0.5085946 ]])

In [10]:
# converting the np array into a dataframe

x_scaled= pd.DataFrame(x_train_scaled, columns= x.columns)
x_scaled

        cgpa        iq
0  -1.639761 -1.446429
1  -1.810792 -1.518570
2  -1.041152 -0.941441
3  -0.528059 -0.869300
4  -1.212183 -1.013582
5   1.182253  1.583497
6  -0.528059 -0.580736
7   1.011222  0.645663
8   0.583644  0.357098
9  -1.554246 -1.374288
10  1.438800  1.799920
11  0.925706  0.934227
12  0.156066 -0.075748
13  0.754675  0.284957
14 -0.014965 -0.220030
15  0.412613  0.212816
16 -0.613574 -0.725018
17  1.609831  2.088484
18 -0.357028 -0.292171
19 -1.468730 -1.157864
20  1.353284  1.583497
21  1.182253  1.439215
22  1.267769  1.367073
23 -1.725277 -1.590711
24  1.438800  1.727779
25  0.241582  0.068534
26  0.669159  0.429239
27 -0.271512 -0.364312
28  0.156066  0.140675
29  0.669159  0.573522
30  0.070550 -0.147889
31  0.498128  0.284957
32 -0.955637 -0.797159
33  0.327097 -0.003607
34 -1.297699 -1.230005
35 -1.126668 -1.085723
36  0.840191  0.717804
37  0.498128  0.140675
38 -0.699090 -0.436454
39 -0.442543 -0.508595

In [11]:
x.columns  # we can give columns name while creating dataframe by using the list

Index(['cgpa', 'iq'], dtype='object')

In [12]:
#Train the model
from sklearn.linear_model import LogisticRegression

model= LogisticRegression()

model.fit(x_scaled, y_train)

LogisticRegression()

In [13]:
x_test_scaled= pd.DataFrame(x_test_scaled, columns= x.columns
                            )
x_test_scaled

       cgpa        iq
0  1.096737  1.150650
1  1.524315  1.872061
2  1.695346  2.304907
3  0.925706  0.862086
4  0.412613  0.212816
5  1.096737  1.294932
6 -1.383215 -1.302146
7 -0.784605 -0.652877
8 -0.870121 -0.797159
9  0.754675  0.501380

In [14]:
y_pred= model.predict(x_test_scaled)
y_pred

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 1])

In [15]:
y_test

3     1
26    1
40    1
1     1
49    1
45    1
18    0
16    0
38    0
29    1
Name: scholarship, dtype: int64

# Normalization
## MinMaxScaling
 - squeezes all data in range 0 to 1

In [16]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(x, df['scholarship'], train_size= 0.8)

In [20]:
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()

scaler.fit(x_train)

x_train_scaled= scaler.transform(x_train)
x_test_scaled= scaler.transform(x_test)

In [21]:
pd.DataFrame(x_train_scaled, columns= x.columns)

     cgpa        iq
0   0.850  0.777778
1   0.975  0.944444
2   0.625  0.462963
3   0.400  0.333333
4   0.850  0.814815
5   0.650  0.444444
6   0.175  0.129630
7   0.800  0.574074
8   0.250  0.203704
9   0.150  0.148148
10  1.000  1.000000
11  0.550  0.388889
12  0.350  0.259259
13  0.675  0.500000
14  0.725  0.537037
15  0.725  0.481481
16  0.625  0.462963
17  0.200  0.166667
18  0.300  0.296296
19  0.825  0.703704
20  0.050  0.055556
21  0.775  0.629630
22  0.650  0.481481
23  0.000  0.000000
24  0.750  0.592593
25  0.500  0.351852
26  0.575  0.425926
27  0.925  0.851852
28  0.375  0.277778
29  0.525  0.370370
30  0.100  0.074074
31  0.875  0.759259
32  0.825  0.740741
33  0.025  0.037037
34  0.775  0.648148
35  0.550  0.444444
36  0.225  0.203704
37  0.425  0.314815
38  0.275  0.240741
39  0.075  0.111111