In [13]:
import pandas as pd
import numpy as np

In [14]:
df= pd.read_csv("datasets/mixed_data.csv")

In [15]:
df.sample(5)

    ID  Code_Info Mixed_Num_Letter  Department  Salary
14  15         35                2          IT   81000
16  17        F23                3          HR   54000
13  14        E67                l  Management   97000
5    6  Mid-level                2          HR   52000
8    9         31                k  Management   90000

In [16]:
df['Code_Info'].unique()  #gives what are the unique values in the column

array(['A56', 'Senior', '28', 'g78', '40', 'Mid-level', 'B12', 'Junior',
       '31', 'c99', 'D45', '27', 'E67', '35', 'F23', '33', 'G89'],
      dtype=object)

In [17]:
df['Code_Info'].nunique()  #gives te number of unique values in the column

17

In [18]:
## for the column not having the numeric value and Alphabetic value in same cell

#extract numeric part
df['Mixed_Num_Letter_Numeric']= pd.to_numeric(df['Mixed_Num_Letter'], errors= "coerce", downcast= 'integer')

In [19]:
# extract the categorical part
df['Mixed_Num_Letter_category']= np.where(df['Mixed_Num_Letter_Numeric'].isnull(), df['Mixed_Num_Letter'], np.nan)

In [20]:
df.head()

,ID,Code_Info,Mixed_Num_Letter,Department,Salary,Mixed_Num_Letter_Numeric,Mixed_Num_Letter_category
0,1,A56,1,HR,50000,1.0,NaN
1,2,Senior,g,IT,75000,NaN,g
2,3,28,4,Finance,62000,4.0,NaN
3,4,g78,j,IT,80000,NaN,j
4,5,40,5,Management,95000,5.0,NaN

In [23]:
# for having numerical and categorical in same cell
df['Code_Info_Numeric']= df['Code_Info'].str.extract('(\d+)')   #captures numeric part
df["Code_Info_Categorical"]= df['Code_Info'].str[0]    #extracts first element

In [24]:
df.head()

,ID,Code_Info,Mixed_Num_Letter,Department,Salary,Mixed_Num_Letter_Numeric,Mixed_Num_Letter_category,Code_Info_Numeric,Code_Info_Categorical
0,1,A56,1,HR,50000,1.0,NaN,56,A
1,2,Senior,g,IT,75000,NaN,g,NaN,S
2,3,28,4,Finance,62000,4.0,NaN,28,2
3,4,g78,j,IT,80000,NaN,j,78,g
4,5,40,5,Management,95000,5.0,NaN,40,4